### ISSUE TITLE
a lot of type inference bugs fixed in kotlin 1.4 when to drop support for 1.2?

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#51]
I saw that a lot of the inference type bugs I listed here: https://github.com/robstoll/atrium#kotlin-bugs, are fixed in the new type inference implementation. The new type inference algorithm should land in Kotlin with 1.4. 
Atrium does not build with the new type inference system (not our fault) and Jetbrains has no targeted to fix the problems with 1.4 as well. So far so good, looking forward to 1.4

Thus the question for us, we are currently still supporting 1.2 and are not using new features of 1.3 for this very same reason. How do we want to proceed for Kotlin 1.4?

I would suggest that we do the same as for 1.3, add an extension and only drop support for 1.2 once we introduce Atrium 1.0.0 (and I would probably skip kotlin 1.3 and go straight to the newest Kotlin version). Thoughts?

**Comment by jGleitz** [comment]
From my point of view, atrium is still in a beta phase, as clearly indicated by having a 0.x version number. Because of that, I do not have high expectations regarding backwards compatibility. As we can see from the discussions in this repository, there are still elementary parts of atrium that are not quite settled.

I am voting for switching to Kotlin 1.4 as soon as IDE support is sufficient. I agree that we can simply not use features from 1.3 until then.

However, I think that we should have a 0.x version that already supports Kotlin 1.4 to have some time to see if any bugs emerge. If we can keep support for Kotlin 1.2 in that version easily, we should. But if it is advantageous to drop 1.2 or even 1.3, I feel like development speed is currently more important than backwards compatibility.

**Comment by robstoll** [comment]
I thought this over and I came to the conclusion that I am in favour of dropping Kotlin 1.2 support before 1.0.0 if certain conditions are met.
The new type inference will hopefully allow that we can provide a better API especially in the area of feature assertions. Yet, I am not entirely convinced though that it will fix the major issues we have. Thus I will wait until Kotlin 1.4 is out, check if it would allow to have a better API and decide then. 
What I will already do on the other hand is inform the Atrium users that we might drop support for Kotlin 1.2 and 1.3 once Kotlin 1.4 is out.

**Comment by robstoll** [comment]
After the discussion in #61, I think it makes more sense to drop support with 1.0.0 but it also makes sense to introduce 1.0.0 earlier than thought so far. So either we drop support with 1.0.0 in case Kotlin 1.4 is already out by then or we are going to drop it with 2.0.0

**Comment by robstoll** [comment]
going to drop it with 0.20.0

**Comment by robstoll** [comment]
dropped support for kotlin 1.2 in v1.1.0 and support for kotlin 1.3 in v1.2.0
