### ISSUE TITLE
rename toBe to equals_ or equalz?

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#59]
I love `toBe` for being short and fast to write, much better than `isEqualTo` as in AssertJ. As there are users confusing toBe with `isSameAs`, I was asking myself if we should rename it to `equals_`
it's a tad longer but that's fine IMO. However writing `_` slows down my speed, that's the reason why I was also thinking about `equalz`. the down-side of `equalz` it can quickly be confused with `equals` :smile: 
Following in comparison
```
expect(1).toBe(2)

expect(1).equals_(2)

expect(s).equalz(2)
```

Thoughts?

**Comment by jGleitz** [comment]
I don’t know… we spend a lot of time on making the API fluent and then we start using something that is not even a proper word? For one of the most used assertions? I really don’t like it.

I think `toBe` is fine. `isEqualTo` is also very fin for me. Unfortunately, Hamcrest’s `is` not an option because it is a keyword in Kotlin.

**Comment by robstoll** [comment]
Good let's keep toBe. I would have taken `is` in the first place but as you said, its a keyword. Upvote https://youtrack.jetbrains.com/issue/KT-25250 maybe we can use it for other purposes one day. And add use cases if you have more
